---
- name: install jenkins master
  hosts: jenkins-master

  pre_tasks:
  - import_tasks: jenkins-master-packages.yml    

  roles:
  - role: ansible-role-java
    become: yes
    
  - role: ansible-role-ssl-certs
    become: yes

  - role: ansible-role-apache
    become: yes

  - role: ansible-role-jenkins-master
    become: yes

  - role: ansible-role-terraform
    become: yes 

  - role: ansible-role-ansible
    become: yes      

  post_tasks:
  - import_tasks: swap.yml   
  - import_tasks: jenkins-master-az-cli.yml   
  - import_tasks: jenkins-master-reverse-proxy.yml
  - import_tasks: jenkins-master-restart-services.yml
  - import_tasks: jenkins-master-wait-startup.yml
  - import_tasks: jenkins-master-hashicorp-vault.yml
  - import_tasks: jenkins-master-jcasc.yml
  - import_tasks: jenkins-master-restart-services.yml
  - import_tasks: jenkins-master-wait-startup.yml
  - import_tasks: jenkins-master-fixes.yml
  - import_tasks: jenkins-master-build-jobs.yml  