---
ansible_connection: local

test: testing

cloud_variables:
  azure:
    resource_group_name: "aks_demo_{{ ansible_user_id }}"
    location: ukwest
    nsg_source_address_prefix: "{{ ((terraform_source_ip is defined) and (terraform_source_ip | length > 0)) | ternary(terraform_source_ip,'*') }}"
    admin_username: cloud_admin
    ssh_key_data: "{{ ansible_user_dir }}/.ssh/aks_demo.pub"
    lb_frontend_port: "80"

cloud_environment:
  azure:
    TF_DATA_DIR: "./terraform_files/azure/"
#    ARM_SUBSCRIPTION_ID: "{{ lookup('env', 'ARM_SUBSCRIPTION_ID') }}"
#    ARM_CLIENT_ID: "{{ lookup('env', 'ARM_CLIENT_ID') }}"
#    ARM_CLIENT_SECRET: "{{ lookup('env', 'ARM_CLIENT_SECRET') }}"
#    ARM_TENANT_ID: "{{ lookup('env', 'ARM_TENANT_ID') }}"
#    TF_VAR_ssh_key_data: "{{ lookup('env','WORKSPACE') }}/files/azure.pub"