---
# jenkins role variables
jenkins_hostname: localhost
jenkins_http_port: 8080
jenkins_url_prefix: ""
jenkins_connection_delay: 5
jenkins_connection_retries: 60

# jenkins_version: "2.131"
jenkins_plugin_timeout: 300
jenkins_plugins:
  - active-directory
  - ansicolor
  - blueocean
  - build-timeout
  - configuration-as-code
  - configuration-as-code-support  
  - credentials-binding
  - git
  - greenballs
  - job-dsl
  - ldap
  - matrix-auth
  - monitoring
  - nunit
  - pam-auth
  - pipeline-input-step
  - pipeline-stage-view
  - role-strategy
  - saml
  - timestamper
  - workflow-aggregator
  - workflow-multibranch
  - ws-cleanup


jenkins_admin_password: "admin"
jenkins_credential_secret_text_entries:
  - id: ansible_vault
    description: 'Ansible Vault credential'
    secret_text: "{{ vault_password }}"

# variable for reading inventory and jcasc
static_inventory_file: "{{ playbook_dir }}/inventory/default"
static_inventory_dump: "{{ playbook_dir }}/scripts/get-inventory.py"

jenkins_innersource_vra_project_key: ""
jenkins_slave_ssh_private_key: ""
jenkins_azure_slave_ssh_private_key: ""

jenkins_jcasc_vault_file: '/var/lib/jenkins/secrets/vault.file'
jenkins_jcasc_vault_token: 'ATOKEN'
jenkins_jcasc_vault_url: 'http://127.0.0.1:8200'
jenkins_jcasc_vault_path: 'kv/jenkins/master'

jenkins_global_environment_variables:
  - {key: 'CASC_VAULT_FILE', value: '/var/lib/jenkins/secrets/vault.file' }


# apache variables
apache_role_server_admin: admins@cloud-msp.net

# ansible variables
ansible_install_method: 'pip'
ansible_install_version_pip: '2.7.1'
ansible_install_pip_package: 'ansible[azure]'

# ansible-role-ssl-certs role facts
ssl_certs_path: /etc/ssl/certs
ssl_certs_locality: "Chicago"
ssl_certs_organization: "Contoso"
ssl_certs_state: "IL"
ssl_certs_days: "730"
ssl_certs_path_owner: "root"
ssl_certs_path_group: "root"  